/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Staff;

import Database.DatabaseManager;
import Tools.FormatText;
import Tools.IDGenerator;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Hashtable;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class JpTaoHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form JpTaoHoaDon
     */
    
    private DatabaseManager database = new DatabaseManager("BitSneaker");
    
    public JpTaoHoaDon(String username) {
        initComponents();
        
//        Hashtable<String, String> logininformation = new Hashtable<String, String>();
        
        txtMaHoaDon.setText(IDGenerator.generateSellOrderID("staff"));
        txtMaHoaDon.setEditable(false);

        btnThemHD.setVisible(false);
        inThongTinNhanVien(username);
        layTGHienTai();
        //layDSSanPham();
        tinhTongThanhTien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTaoHoaDon = new javax.swing.JPanel();
        lblMaHoaDon = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        lblThoiGianTaoHD = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMaNhanVien = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSSPTrongHD = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        lblTongThanhTien = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        jpThem = new javax.swing.JPanel();
        lblThem = new javax.swing.JLabel();
        lblMaSP = new javax.swing.JLabel();
        txtMaSanPham = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblSL = new javax.swing.JLabel();
        lblDV = new javax.swing.JLabel();
        lblPL = new javax.swing.JLabel();
        spinSoLuong = new javax.swing.JSpinner();
        lblTenSanPham = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblMau = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        lblDonVi = new javax.swing.JLabel();
        lblPhanLoai = new javax.swing.JLabel();
        lblHinhAnh = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        lblTenNhanVien = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnThemHD = new javax.swing.JButton();
        btnReload = new javax.swing.JButton();
        btnThemSP = new javax.swing.JButton();
        btnRemove = new javax.swing.JToggleButton();

        jpTaoHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        lblMaHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaHoaDon.setText("Mã hóa đơn:");

        txtMaHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblThoiGianTaoHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Thời gian tạo hóa đơn:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nhân viên tạo hóa đơn:");

        lblMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel13.setText("DANH SÁCH CÁC SẢN PHẨM TRONG HÓA ĐƠN");

        tblDSSPTrongHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Brand", "Màu", "Size", "Số lượng", "Đơn giá", "Giá thành"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSSPTrongHD.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblDSSPTrongHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSSPTrongHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSSPTrongHD);

        jLabel11.setBackground(new java.awt.Color(204, 204, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Tổng thành tiền");

        lblTongThanhTien.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btnThanhToan.setBackground(new java.awt.Color(204, 204, 255));
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThanhToan.setText("THANH TOÁN");
        btnThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThanhToanMouseClicked(evt);
            }
        });

        jpThem.setBackground(new java.awt.Color(255, 255, 255));

        lblThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblThem.setText("Thêm sản phẩm");

        lblMaSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaSP.setText("Mã sản phẩm:");

        txtMaSanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSanPhamActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Tên sản phẩm:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Brand:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Màu:");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Size:");

        lblSL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSL.setText("Số lượng:");

        lblDV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDV.setText("Đơn vị:");

        lblPL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPL.setText("Phân loại:");

        jLabel.setText("Hình ảnh:");

        javax.swing.GroupLayout jpThemLayout = new javax.swing.GroupLayout(jpThem);
        jpThem.setLayout(jpThemLayout);
        jpThemLayout.setHorizontalGroup(
            jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpThemLayout.createSequentialGroup()
                        .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel)
                            .addComponent(lblSL, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDV, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227))
                    .addGroup(jpThemLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(286, 286, 286))
                    .addGroup(jpThemLayout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(286, 286, 286))
                    .addGroup(jpThemLayout.createSequentialGroup()
                        .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThem)
                            .addGroup(jpThemLayout.createSequentialGroup()
                                .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator1)
                                        .addComponent(lblTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblMau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblDonVi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblPhanLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblHinhAnh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spinSoLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpThemLayout.createSequentialGroup()
                        .addComponent(lblPL, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpThemLayout.setVerticalGroup(
            jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpThemLayout.createSequentialGroup()
                        .addComponent(lblThem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpThemLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpThemLayout.createSequentialGroup()
                        .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPhanLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(jLabel))
                .addContainerGap())
        );

        lblTenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mã nhân viên:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tên nhân viên:");

        btnThemHD.setBackground(new java.awt.Color(204, 204, 255));
        btnThemHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThemHD.setText("HÓA ĐƠN MỚI");
        btnThemHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemHDMouseClicked(evt);
            }
        });

        btnReload.setBackground(new java.awt.Color(204, 204, 255));
        btnReload.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReload.setIcon(new javax.swing.ImageIcon("src//main//java//res//iconStaff//reload.png"));
        btnReload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReloadMouseClicked(evt);
            }
        });
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        btnThemSP.setBackground(new java.awt.Color(204, 204, 255));
        btnThemSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThemSP.setText("THÊM ");
        btnThemSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemSPMouseClicked(evt);
            }
        });
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });

        btnRemove.setText("Loại");
        btnRemove.setEnabled(false);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpTaoHoaDonLayout = new javax.swing.GroupLayout(jpTaoHoaDon);
        jpTaoHoaDon.setLayout(jpTaoHoaDonLayout);
        jpTaoHoaDonLayout.setHorizontalGroup(
            jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTaoHoaDonLayout.createSequentialGroup()
                .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTaoHoaDonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpTaoHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblThoiGianTaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpTaoHoaDonLayout.createSequentialGroup()
                                .addComponent(lblMaHoaDon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpTaoHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27)
                                .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(28, 28, 28)
                                .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMaNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTenNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpTaoHoaDonLayout.createSequentialGroup()
                        .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpTaoHoaDonLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpTaoHoaDonLayout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabel13))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTaoHoaDonLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpTaoHoaDonLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(btnThemHD)
                                        .addGap(35, 35, 35)
                                        .addComponent(btnThanhToan))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTaoHoaDonLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(14, 14, 14)
                                        .addComponent(lblTongThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jpTaoHoaDonLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnRemove)))
                        .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpTaoHoaDonLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jpThem, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpTaoHoaDonLayout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(btnThemSP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpTaoHoaDonLayout.setVerticalGroup(
            jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTaoHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpTaoHoaDonLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblThoiGianTaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove)
                        .addGap(10, 10, 10)
                        .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTongThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThanhToan)
                            .addComponent(btnThemHD)))
                    .addGroup(jpTaoHoaDonLayout.createSequentialGroup()
                        .addComponent(jpThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jpTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThemSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(3, 3, 3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

//    public int kiemTraAccount(String accountID, String password, String type){
//        
//        int kq = -1;
//        
//        try {
//            ResultSet rs = database.queryData("SELECT AccountID, Password, Type FROM ACCOUNT WHERE AccountID = ('"+accountID+"') AND Password = ('"+password+"') AND Type =('"+type+"')");
//            if(rs.next()){
//                kq = 1;
//            }
//        } catch (SQLException ex) {
//            System.out.println("Lỗi hàm kiểm tra tài khoản");
//        }
//        return kq;
//    }
    
    public void inThongTinNhanVien(String accountID){
        
        Vector vt;
        try {
            ResultSet rs = database.queryData("SELECT StaffID, CONCAT_WS(' ',FirstName,LastName) FROM STAFF "
                    + "WHERE STAFF.AccountID = ('"+accountID+"')");
            while(rs.next()){
                lblMaNhanVien.setText(rs.getString(1));
                lblTenNhanVien.setText(rs.getString(2));
            }
        } catch (SQLException ex) {
            System.out.println("Lỗi hàm in thông tin nhân viên");
        }
    }
    
    public void layTGHienTai() {
        String thoiGian = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime());       
        lblThoiGianTaoHD.setText(thoiGian);
    }  
       
//    public void layDSSanPham() {
//        DefaultTableModel dtm = (DefaultTableModel) tblDSSPTrongHD.getModel();
//        dtm.setNumRows(0);
//        Vector vt;
        
//        String sql = "SELECT SNEAKER.Image, SNEAKER.Name, SNEAKER.Brand, SNEAKER.Color, SNEAKER.Size FROM SNEAKER INNER JOIN SELLDETAILS ON SNEAKER.SneakerID = SELLDETAILS.SneakerID";
//        String sql1 = "SELECT SELLDETAILS.Amount FROM SELLDETAILS INNER JOIN SELLORDER ON SELLDETAILS.SellID = SELLORDER.SellID";
//        String sql2 = "SELECT PRICE.SellPrice, PRICE.SellPrice * SELLDETAILS.Amount * (SELLDETAILS.Sale / 100) AS TotalPrice FROM PRICE INNER JOIN SELLDETAILS ON PRICE.SneakerID = SELLDETAILS.SneakerID";
//        try {
//            ResultSet rs = database.queryData(sql);
//            ResultSet rs1 = database.queryData(sql1);
//            ResultSet rs2 = database.queryData(sql2);

//            while(rs.next() && rs1.next() && rs2.next()){
//                vt = new Vector();
//                vt.add(rs.getString("Image"));
//                vt.add(rs.getString("Name"));
//                vt.add(rs.getString("Brand"));
//                vt.add(rs.getString("Color"));
//                vt.add(rs.getString("Size"));
//                vt.add(rs1.getString("Amount"));
//                vt.add(rs2.getString("SellPrice"));
//                vt.add(rs2.getString("TotalPrice"));
//                dtm.addRow(vt);           
//                tblDSSPTrongHD.setModel(dtm);
//            } 
       
//        } catch (SQLException ex) {
//            Logger.getLogger(JpTaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
//        }       
//    }
    
    public int kiemTraMaSPTonTai(String sneakerID) {       
        
        int tonTai = 0;
        String sql = "SELECT * FROM SNEAKER WHERE SneakerID ='" + sneakerID + "'";
        try {
            
            ResultSet rs = database.queryData(sql);
            if(rs.next()){
                tonTai = 1;
            }
            rs.close();
            
        }
        catch (SQLException ex) {
            Logger.getLogger(JpTaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tonTai;
    }
    
    public void themHoaDon(String sellID){
        
        String sql = "insert into SELLORDER (SellID, StaffID, TimeCreate, TimePaid, Status) values('"+sellID+"', '"+lblMaNhanVien.getText()+"', getdate(), getdate(), '"+"paid"+"')";
        database.queryUpdate(sql);
        for(int i=0; i<this.tblDSSPTrongHD.getRowCount(); i++){
            System.out.println("Them sp");
            System.out.println("Sp: "+this.tblDSSPTrongHD.getValueAt(i, 0)+" - "+this.tblDSSPTrongHD.getValueAt(i, 5));
            themSanPham(sellID, this.tblDSSPTrongHD.getValueAt(i, 0)+"", this.tblDSSPTrongHD.getValueAt(i, 5)+"");
        }
    }
    
    public void themSanPham(String sellID, String sneakerID, String amount){
        
        String sql = "insert into SELLDETAILS (SellID, SneakerID, Amount) values('"+sellID+"', '"+sneakerID+"', '"+amount+"')";
        String sql1 = "UPDATE SNEAKER SET Amount = (Amount - "+amount+") WHERE SneakerID = '"+sneakerID+"'";
        database.queryUpdate(sql);
        database.queryUpdate(sql1);
        
    }  
    
    public void hienThiThongTinSP(String sneakerID) {      
        String sql = "SELECT * FROM SNEAKER WHERE SneakerID ='"+sneakerID+"'";
        try {
            
            ResultSet rs = database.queryData(sql);
            while(rs.next()) {
                lblTenSanPham.setText(rs.getString("Name"));
                lblBrand.setText(rs.getString("Brand"));
                lblMau.setText(rs.getString("Color"));
                lblSize.setText(rs.getString("Size"));
                lblDonVi.setText(rs.getString("Unit"));
                lblPhanLoai.setText(rs.getString("Category"));
                String pathHA = rs.getString("Image");
                String path = "src//main//java//res//goods//"+pathHA;  
                ImageIcon imgIcon = new ImageIcon(path);
                Image img = imgIcon.getImage().getScaledInstance(lblHinhAnh.getWidth(), lblHinhAnh.getHeight(), java.awt.Image.SCALE_SMOOTH);
                ImageIcon mainImg = new ImageIcon(img);
                lblHinhAnh.setIcon(mainImg);                             
           }
        } catch (SQLException ex) {
            Logger.getLogger(JpTaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }
    
    public void tinhTongThanhTien(){
        long tong = 0;
        for(int i = 0; i < tblDSSPTrongHD.getRowCount(); i++){
            tong += FormatText.convertFormatTextToLong(tblDSSPTrongHD.getValueAt(i, 7)+"");
        }
        this.lblTongThanhTien.setText(FormatText.covertCurrentcyFormat(tong));
    }
    
    private void tblDSSPTrongHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSSPTrongHDMouseClicked
        // TODO add your handling code here:
        lblThem.setText("Thông tin sản phẩm trong hóa đơn");
//        btnThemSP.setVisible(false);
//        btnReload.setVisible(false);
//        lblMaSP.setVisible(false);
//        txtMaSanPham.setVisible(false);
        lblDV.setText("Đơn giá:");
        lblPL.setText("Giá thành:");
        btnRemove.setEnabled(true);
//        lblMaHoaDon.setVisible(false);
//        txtMaHoaDon.setVisible(false);
//        spinSoLuong.setVisible(false);
//        btnThemHD.setVisible(true);           

        DefaultTableModel dtm=(DefaultTableModel) tblDSSPTrongHD.getModel();
        int i = tblDSSPTrongHD.getSelectedRow();
        
        ResultSet rs = database.queryData("SELECT Image FROM SNEAKER WHERE SneakerID = '"+((String) dtm.getValueAt(i, 0))+"'");
        String pathHA="";
        
        try {
            rs.next();
            pathHA = rs.getString(1);
            String path = "src//main//java//res//goods//"+pathHA;
            ImageIcon imgIcon = new ImageIcon(path);
            Image img = imgIcon.getImage().getScaledInstance(lblHinhAnh.getWidth(), lblHinhAnh.getHeight(), java.awt.Image.SCALE_SMOOTH);
            ImageIcon mainImg = new ImageIcon(img);
            lblHinhAnh.setIcon(mainImg);
        } catch (SQLException ex) {
            Logger.getLogger(JpTaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }


        txtMaSanPham.setText((String) dtm.getValueAt(i, 0));
//        lblHA.setText(pathHA);
        lblTenSanPham.setText((String) dtm.getValueAt(i, 1));
        lblBrand.setText((String) dtm.getValueAt(i, 2));
        lblMau.setText((String) dtm.getValueAt(i, 3));
        lblSize.setText((String) dtm.getValueAt(i, 4));
        lblSoLuong.setText((String) dtm.getValueAt(i, 5));
        lblDonVi.setText((String) dtm.getValueAt(i, 6));
        lblPhanLoai.setText((String) dtm.getValueAt(i, 7));
    }//GEN-LAST:event_tblDSSPTrongHDMouseClicked

    private void btnThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhToanMouseClicked
        // TODO add your handling code here:
        if(this.tblDSSPTrongHD.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "Hóa đơn rỗng");
        }
        else{
            String maHD = txtMaHoaDon.getText();
            themHoaDon(maHD);
            this.btnThemHD.setVisible(true);
            this.btnThanhToan.setVisible(false);
        }
    }//GEN-LAST:event_btnThanhToanMouseClicked

    private void txtMaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSanPhamActionPerformed

    private void btnThemSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemSPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemSPMouseClicked

    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        // TODO add your handling code here:
        String maSP = txtMaSanPham.getText();
        String maHD = txtMaHoaDon.getText();

        if(maSP.equals("") && maHD.equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin hóa đơn!");
        }
        else if(maSP.equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã sản phẩm");
        }
        else if(maHD.equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã hóa đơn");
        }
        else {
            if(kiemTraMaSPTonTai(maSP) == 0) {
                JOptionPane.showMessageDialog(this, "Sản phẩm này không tồn tại");
            }
            else {
                if((int)spinSoLuong.getValue() < 1){
                    JOptionPane.showMessageDialog(this, "Số lượng sản phẩm không hợp lệ");
                }

                else {
                    hienThiThongTinSP(maSP);
                    this.layTGHienTai();
                    themVaoBang(maSP);
                    this.tinhTongThanhTien();
                    btnThemHD.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_btnThemSPActionPerformed

    private void themVaoBang(String id){
        DefaultTableModel dtm = (DefaultTableModel) tblDSSPTrongHD.getModel();
        ResultSet rs = database.queryData("SELECT * FROM PRICE WHERE SneakerID ='"+id+"'");
        try {
            rs.next();
            Vector vt = new Vector();
            vt.add(id);
            vt.add(lblTenSanPham.getText());
            vt.add(lblBrand.getText());
            vt.add(lblMau.getText());
            vt.add(lblSize.getText());
            vt.add(spinSoLuong.getValue());
            vt.add(FormatText.covertCurrentcyFormat(rs.getLong(3)));
            vt.add(FormatText.covertCurrentcyFormat(rs.getLong(3)*((int)spinSoLuong.getValue())));
            dtm.addRow(vt);
        } catch (SQLException ex) {
            Logger.getLogger(JpTaoHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        tblDSSPTrongHD.setModel(dtm);
    }
    
    private void btnReloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReloadMouseClicked
        // TODO add your handling code here:
//        txtMaHoaDon.setText("");
        txtMaSanPham.setText("");
        lblTenSanPham.setText("");
        lblBrand.setText("");
        lblSize.setText("");
        lblMau.setText("");
        lblDonVi.setText("");
        lblPhanLoai.setText("");
        lblHinhAnh.setText("");
        spinSoLuong.setValue(0);
    }//GEN-LAST:event_btnReloadMouseClicked

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReloadActionPerformed

    private void btnThemHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemHDMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblDSSPTrongHD.getModel();
        dtm.setRowCount(0);
        tblDSSPTrongHD.setModel(dtm);
        lblThem.setText("Thêm sản phẩm");
        btnThemSP.setVisible(true);
        btnReload.setVisible(true);
        lblMaSP.setVisible(true);
        txtMaSanPham.setVisible(true);
        txtMaSanPham.setText("");
        lblTenSanPham.setText("");
        lblBrand.setText("");
        lblMau.setText("");
        lblSize.setText("");
        spinSoLuong.setValue(0);
        lblSoLuong.setText("");
        lblDV.setVisible(true);
        lblDonVi.setText("");
        lblPL.setVisible(true);
        lblPhanLoai.setText("");
        lblMaHoaDon.setVisible(true);
        txtMaHoaDon.setVisible(true);
        txtMaHoaDon.setText("");
        spinSoLuong.setVisible(true);
        this.btnThemHD.setVisible(false);
    }//GEN-LAST:event_btnThemHDMouseClicked

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dtm = (DefaultTableModel) this.tblDSSPTrongHD.getModel();
        dtm.removeRow(this.tblDSSPTrongHD.getSelectedRow());
        
        this.tblDSSPTrongHD.setModel(dtm);
        this.tinhTongThanhTien();
        btnRemove.setEnabled(false);
    }//GEN-LAST:event_btnRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReload;
    private javax.swing.JToggleButton btnRemove;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemHD;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel jpTaoHoaDon;
    private javax.swing.JPanel jpThem;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblDV;
    private javax.swing.JLabel lblDonVi;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblMau;
    private javax.swing.JLabel lblPL;
    private javax.swing.JLabel lblPhanLoai;
    private javax.swing.JLabel lblSL;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lblTenSanPham;
    private javax.swing.JLabel lblThem;
    private javax.swing.JLabel lblThoiGianTaoHD;
    private javax.swing.JLabel lblTongThanhTien;
    private javax.swing.JSpinner spinSoLuong;
    private javax.swing.JTable tblDSSPTrongHD;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtMaSanPham;
    // End of variables declaration//GEN-END:variables
}
